// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLineItem(arg1) {
  return window['go']['main']['App']['AddLineItem'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateEstimate(arg1) {
  return window['go']['main']['App']['CreateEstimate'](arg1);
}

export function CreateManualQuote(arg1) {
  return window['go']['main']['App']['CreateManualQuote'](arg1);
}

export function CreatePriceListItem(arg1) {
  return window['go']['main']['App']['CreatePriceListItem'](arg1);
}

export function CreateTaxRate(arg1) {
  return window['go']['main']['App']['CreateTaxRate'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteEstimate(arg1) {
  return window['go']['main']['App']['DeleteEstimate'](arg1);
}

export function DeleteLineItem(arg1) {
  return window['go']['main']['App']['DeleteLineItem'](arg1);
}

export function DeleteManualQuote(arg1) {
  return window['go']['main']['App']['DeleteManualQuote'](arg1);
}

export function DeletePriceListItem(arg1) {
  return window['go']['main']['App']['DeletePriceListItem'](arg1);
}

export function DeleteTaxRate(arg1) {
  return window['go']['main']['App']['DeleteTaxRate'](arg1);
}

export function GenerateEstimatePDF(arg1, arg2) {
  return window['go']['main']['App']['GenerateEstimatePDF'](arg1, arg2);
}

export function GenerateProposalPDF(arg1, arg2) {
  return window['go']['main']['App']['GenerateProposalPDF'](arg1, arg2);
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllCategoriesWithItems() {
  return window['go']['main']['App']['GetAllCategoriesWithItems']();
}

export function GetAllCustomers() {
  return window['go']['main']['App']['GetAllCustomers']();
}

export function GetAllEstimates() {
  return window['go']['main']['App']['GetAllEstimates']();
}

export function GetAllManualQuotes() {
  return window['go']['main']['App']['GetAllManualQuotes']();
}

export function GetAllPriceListItems() {
  return window['go']['main']['App']['GetAllPriceListItems']();
}

export function GetAllTaxRates() {
  return window['go']['main']['App']['GetAllTaxRates']();
}

export function GetCategory(arg1) {
  return window['go']['main']['App']['GetCategory'](arg1);
}

export function GetCompanySettings() {
  return window['go']['main']['App']['GetCompanySettings']();
}

export function GetCustomer(arg1) {
  return window['go']['main']['App']['GetCustomer'](arg1);
}

export function GetCustomersPage(arg1) {
  return window['go']['main']['App']['GetCustomersPage'](arg1);
}

export function GetEstimate(arg1) {
  return window['go']['main']['App']['GetEstimate'](arg1);
}

export function GetEstimatesByCustomer(arg1) {
  return window['go']['main']['App']['GetEstimatesByCustomer'](arg1);
}

export function GetEstimatesPage(arg1) {
  return window['go']['main']['App']['GetEstimatesPage'](arg1);
}

export function GetManualQuote(arg1) {
  return window['go']['main']['App']['GetManualQuote'](arg1);
}

export function GetManualQuotesPage(arg1) {
  return window['go']['main']['App']['GetManualQuotesPage'](arg1);
}

export function GetPriceListItem(arg1) {
  return window['go']['main']['App']['GetPriceListItem'](arg1);
}

export function GetPriceListItemsByCategory(arg1) {
  return window['go']['main']['App']['GetPriceListItemsByCategory'](arg1);
}

export function OpenFileInDefaultApp(arg1) {
  return window['go']['main']['App']['OpenFileInDefaultApp'](arg1);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2);
}

export function UpdateCategorySortOrder(arg1) {
  return window['go']['main']['App']['UpdateCategorySortOrder'](arg1);
}

export function UpdateCompanySettings(arg1) {
  return window['go']['main']['App']['UpdateCompanySettings'](arg1);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateEstimate(arg1) {
  return window['go']['main']['App']['UpdateEstimate'](arg1);
}

export function UpdateEstimateSortOrder(arg1) {
  return window['go']['main']['App']['UpdateEstimateSortOrder'](arg1);
}

export function UpdateLineItem(arg1) {
  return window['go']['main']['App']['UpdateLineItem'](arg1);
}

export function UpdateLineItemSortOrder(arg1) {
  return window['go']['main']['App']['UpdateLineItemSortOrder'](arg1);
}

export function UpdateManualQuote(arg1) {
  return window['go']['main']['App']['UpdateManualQuote'](arg1);
}

export function UpdatePriceListItem(arg1, arg2) {
  return window['go']['main']['App']['UpdatePriceListItem'](arg1, arg2);
}

export function UpdatePriceListItemSortOrder(arg1) {
  return window['go']['main']['App']['UpdatePriceListItemSortOrder'](arg1);
}

export function UpdateTaxRate(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaxRate'](arg1, arg2);
}
